<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class ResourcesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('resources')->truncate();
        $statement = "INSERT INTO ".env('DB_PREFIX')."`resources` (`resourceId`, `resourceCode`, `resourceValue`) VALUES
                     (1,\"specialneeds\",\"Physical disability\"),
                    (2,\"specialneeds\",\"Hearing impairment\"),
                    (3,\"specialneeds\",\"Visual impairment\"),
                    (4,\"specialneeds\",\"ADHD\"),
                    (5,\"specialneeds\",\"Autism\"),
                    (6,\"specialneeds\",\"Learning difficulties\"),
                    (7,\"specialneeds\",\"Intellectual disability\"),
                    (8,\"specialneeds\",\"Other\"),
                    (10,\"highesteducation\",\"Intermediate\"),
                    (11,\"highesteducation\",\"Technical - Vocational\"),
                    (12,\"highesteducation\",\"Brevet\"),
                    (13,\"highesteducation\",\"Baccalaureate\"),
                    (14,\"highesteducation\",\"Bachelor Degree\"),
                    (15,\"highesteducation\",\"Masters Degree\"),
                    (16,\"highesteducation\",\"PhD\"),
                    (17,\"major\",\"Accounting\"),
                    (18,\"major\",\"Actuarial Science\"),
                    (19,\"major\",\"Advertising\"),
                    (20,\"major\",\"Agriculture\"),
                    (21,\"major\",\"Agricultural and Biological Engineering\"),
                    (22,\"major\",\"Agricultural Business Management\"),
                    (23,\"major\",\"Agriculture Economics\"),
                    (24,\"major\",\"Animal Bioscience\"),
                    (25,\"major\",\"Animal Sciences\"),
                    (26,\"major\",\"Anthropology\"),
                    (27,\"major\",\"Applied Mathematics\"),
                    (28,\"major\",\"Archaeology\"),
                    (29,\"major\",\"Architectural Engineering\"),
                    (30,\"major\",\"Architecture\"),
                    (31,\"major\",\"Art History\"),
                    (32,\"major\",\"Studio Art\"),
                    (33,\"major\",\"Art Education\"),
                    (34,\"major\",\"Biobehavioral Health\"),
                    (35,\"major\",\"Biochemistry\"),
                    (36,\"major\",\"Bioengineering\"),
                    (37,\"major\",\"Biology\"),
                    (38,\"major\",\"Biophysics\"),
                    (39,\"major\",\"Biotechnology\"),
                    (40,\"major\",\"Business Administration and Management\"),
                    (41,\"major\",\"Business Logistics\"),
                    (42,\"major\",\"Chemical Engineering\"),
                    (43,\"major\",\"Chemistry\"),
                    (44,\"major\",\"Children\"),
                    (45,\"major\",\"Civil Engineering\"),
                    (46,\"major\",\"Computer Engineering\"),
                    (47,\"major\",\"Computer Science\"),
                    (48,\"major\",\"Crime\"),
                    (49,\"major\",\"Dance\"),
                    (50,\"major\",\"Earth Sciences\"),
                    (51,\"major\",\"Economics\"),
                    (52,\"major\",\"Electrical Engineering\"),
                    (53,\"major\",\"Elementary and Kindergarten Education\"),
                    (54,\"major\",\"Engineering Science\"),
                    (55,\"major\",\"Literature\"),
                    (56,\"major\",\"Environmental Systems Engineering\"),
                    (57,\"major\",\"Environmental Sciences\"),
                    (58,\"major\",\"Environmental Resource Management\"),
                    (59,\"major\",\"Film and Video\"),
                    (60,\"major\",\"Finance\"),
                    (61,\"major\",\"Food Science\"),
                    (62,\"major\",\"Forest Science\"),
                    (63,\"major\",\"Forest Technology\"),
                    (64,\"major\",\"General Science\"),
                    (65,\"major\",\"Geography\"),
                    (66,\"major\",\"Geosciences\"),
                    (67,\"major\",\"Graphic Design and Photography\"),
                    (68,\"major\",\"Health and Physical Education\"),
                    (116,\"major\",\"History\"),
                    (117,\"major\",\"Horticulture\"),
                    (118,\"major\",\"Hotel\"),
                    (119,\"major\",\"Human Development and Family Studies\"),
                    (120,\"major\",\"Individual and Family Studies\"),
                    (121,\"major\",\"Industrial Engineering\"),
                    (122,\"major\",\"Information Sciences and Technology\"),
                    (123,\"major\",\"Journalism\"),
                    (124,\"major\",\"Kinesiology\"),
                    (125,\"major\",\"Landscape Architecture\"),
                    (126,\"major\",\"Law Enforcement and Correction\"),
                    (127,\"major\",\"Marine Biology\"),
                    (128,\"major\",\"Marketing\"),
                    (129,\"major\",\"Mathematics\"),
                    (130,\"major\",\"Mechanical Engineering\"),
                    (131,\"major\",\"Media Studies\"),
                    (132,\"major\",\"Meteorology\"),
                    (133,\"major\",\"Microbiology\"),
                    (134,\"major\",\"Mineral Economics\"),
                    (135,\"major\",\"Modern Languages\"),
                    (136,\"major\",\"Music Education\"),
                    (137,\"major\",\"Nuclear Engineering\"),
                    (138,\"major\",\"Nursing\"),
                    (139,\"major\",\"Nutrition\"),
                    (140,\"major\",\"Philosophy\"),
                    (141,\"major\",\"Physics\"),
                    (142,\"major\",\"Physiology\"),
                    (143,\"major\",\"Political Science\"),
                    (144,\"major\",\"Pre-medicine\"),
                    (145,\"major\",\"Psychology\"),
                    (146,\"major\",\"Public Relations\"),
                    (147,\"major\",\"Real Estate\"),
                    (148,\"major\",\"Recreation and Parks\"),
                    (149,\"major\",\"Rehabilitation Services\"),
                    (150,\"major\",\"Religious Studies\"),
                    (151,\"major\",\"Secondary Education\"),
                    (152,\"major\",\"Sociology\"),
                    (153,\"major\",\"Social Work\"),
                    (154,\"major\",\"Special Education\"),
                    (155,\"major\",\"Speech Communication\"),
                    (156,\"major\",\"Speech Pathology and Audiology/Communication Disorder\"),
                    (157,\"major\",\"Statistics\"),
                    (158,\"major\",\"Telecommunications\"),
                    (159,\"major\",\"Theater\"),
                    (160,\"major\",\"Wildlife and Fishery Science\"),
                    (161,\"major\",\"Wildlife Technology\"),
                    (162,\"major\",\"Women's Studies\"),
                    (163,\"language\",\"English\"),
                    (164,\"language\",\"French\"),
                    (165,\"language\",\"Arabic\"),
                    (166,\"technologyplatform\",\"Microsoft Word\"),
                    (167,\"technologyplatform\",\"Microsoft Excel\"),
                    (170,\"technologyplatform\",\"Internet Browsing\"),
                    (180,\"technologyplatform\",\"WordPress\"),
                    (181,\"technologyplatform\",\"Magento\"),
                    (182,\"technologyplatform\",\"Joumla\"),
                    (183,\"technologyplatform\",\"Droopal\"),
                    (189,\"functionalskills\",\"Social Media\"),
                    (190,\"functionalskills\",\"Call Center\"),
                    (191,\"functionalskills\",\"Data Entry / Collection\"),
                    (192,\"functionalskills\",\"Data Validation / Quality Assurance\"),
                    (193,\"functionalskills\",\"Data Cleansing\"),
                    (196,\"functionalskills\",\"Note Taking\"),
                    (197,\"functionalskills\",\"On-sight Survey\"),
                    (198,\"functionalskills\",\"Transcribing\"),
                    (199,\"functionalskills\",\"Content writing\"),
                    (201,\"functionalskills\",\"E-commerce Listing\"),
                    (202,\"functionalskills\",\"Translation\"),
                    (203,\"functionalskills\",\"Scanning and Archiving\"),
                    (204,\"functionalskills\",\"Warehousing\"),
                    (205,\"functionalskills\",\"Warehouse Stock Count\"),
                    (206,\"functionalskills\",\"Office Work\"),
                    (209,\"institutions\",\"LAU Lebanese American University\"),
                    (210,\"institutions\",\"NDU Notre Dame University - Louaize\"),
                    (211,\"institutions\",\"USEK Université Saint-Esprit de Kaslik\"),
                    (212,\"institutions\",\"AUB American University of Beirut\"),
                    (213,\"institutions\",\"LIU Lebanese International University\"),
                    (214,\"trainingcourses\",\"Communication Course\"),
                    (215,\"trainingcourses\",\"Body language\"),
                    (216,\"trainingcourses\",\"Project Management\");";



        DB::unprepared($statement);
    }
}
